set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on

# Copy to clipboard on mouse drag (cross-platform)
if-shell "uname | grep -q Darwin" \
  "bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'" \
  "bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'"

# Reload config shortcut
bind r source-file ~/.tmux.conf \; display "Reloaded!"
