# Enable mouse support
set -g mouse on

# Copy to clipboard on mouse drag
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Reload config shortcut
bind r source-file ~/.tmux.conf \; display "Reloaded!"
